# Generated by ChatGPT to add Cyrillic Uzbek translation columns
from django.db import migrations, models


def copy_uz_to_uz_cyrl(apps, schema_editor):
    Category = apps.get_model('news_app', 'Category')
    News = apps.get_model('news_app', 'News')
    # Copy existing Uzbek content so the new locale is prefilled
    for cat in Category.objects.all():
        if getattr(cat, 'name_uz_cyrl', None) in (None, ''):
            cat.name_uz_cyrl = cat.name_uz
            cat.save(update_fields=['name_uz_cyrl'])
    for news in News.objects.all():
        fields_to_update = []
        if getattr(news, 'title_uz_cyrl', None) in (None, ''):
            news.title_uz_cyrl = news.title_uz
            fields_to_update.append('title_uz_cyrl')
        if getattr(news, 'body_uz_cyrl', None) in (None, ''):
            news.body_uz_cyrl = news.body_uz
            fields_to_update.append('body_uz_cyrl')
        if fields_to_update:
            news.save(update_fields=fields_to_update)


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0012_featuredcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_uz_cyrl',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_uz_cyrl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz_cyrl',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.RunPython(copy_uz_to_uz_cyrl, migrations.RunPython.noop),
    ]
