# Generated by ChatGPT to populate Cyrillic names for categories
from django.db import migrations


def fill_cyrillic_names(apps, schema_editor):
    Category = apps.get_model('news_app', 'Category')
    mapping = {
        "Jamiyat": "Жамият",
        "Jarayon": "Жараён",
        "Faoliyat": "Фаолият",
        "Iqtisodiyot": "Иқтисодиёт",
        "Tibbiyot": "Тиббиёт",
        "Turizm": "Туризм",
        "Oila": "Оила",
        "Biznes": "Бизнес",
    }
    # Limit selected columns to avoid missing legacy columns (e.g., name_en)
    rows = Category.objects.values("id", "name", "name_uz", "name_uz_cyrl")
    for row in rows:
        new_val = (
            mapping.get(row.get("name"))
            or mapping.get(row.get("name_uz"))
        )
        if new_val:
            Category.objects.filter(id=row["id"]).update(name_uz_cyrl=new_val)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0013_add_uz_cyrl_translation_fields'),
    ]

    operations = [
        migrations.RunPython(fill_cyrillic_names, reverse_code=noop),
    ]
