# Generated by Django 5.2.7 on 2025-12-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0015_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
    ]
