# Generated by Codex to add author translation columns
from django.db import migrations, models


def copy_author_to_translations(apps, schema_editor):
    News = apps.get_model('news_app', 'News')
    for news in News.objects.all():
        updates = []
        if getattr(news, 'author_uz', None) in (None, ''):
            news.author_uz = news.author
            updates.append('author_uz')
        if getattr(news, 'author_uz_cyrl', None) in (None, ''):
            base = news.author_uz or news.author
            news.author_uz_cyrl = base
            updates.append('author_uz_cyrl')
        if updates:
            news.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0019_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_uz',
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='author_uz_cyrl',
            field=models.CharField(max_length=200, null=True, blank=True),
        ),
        migrations.RunPython(copy_author_to_translations, migrations.RunPython.noop),
    ]
